# Generated by Django 3.0.5 on 2020-04-13 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('grader', models.IntegerField()),
                ('lengde_min', models.IntegerField()),
                ('starttid', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
