# Generated by Django 3.0.5 on 2020-04-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klesvask', '0002_auto_20200413_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='vask',
            name='vasker',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
