# Generated by Django 3.0.5 on 2020-04-19 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('klesvask', '0006_washqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='washqueue',
            name='regDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
